### ISSUE TITLE
outsource "fieldstats-ldj" tool into a separate repository

### ISSUE THREAD

**Issue by zazi** [efre-lod/efre-lod-elasticsearch-tools#8]
...and probably rename it, e.g., "jsonl-distinctvalues" or similar.
to be able to easily install it (i.e. via pip) and provide it as a simple commandline tool (analogous to, e.g., [esfstats](https://github.com/slub/esfstats) or [jsonl-stats](https://github.com/slub/jsonl-fstats)). probably requires to remove internal dependencies that are maybe not really necessary here. therefore, README needs also to be enhanced.

**Comment by boerni667** [comment]
Work in progress, closing issue in this repository.
[ldj-distinctvalues](https://github.com/slub/ldj-distinctvalues)
